name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update submodules
      run: git submodule update --init
    - name: Check format
      run: make fmt
    - name: Check compilation
      run: make all-via-docker
